name: Public Release to npmjs.com

on:
  workflow_dispatch:
    branches:
      - main
      - beta

jobs:
  release:
    name: branch - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment:
      name: publishEnv
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci
